# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       libXpm

# >> macros
# << macros

Summary:    X.Org X11 libXpm runtime library
Version:    3.5.10
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org/
Source0:    http://xorg.freedesktop.org/releases/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXpm.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xau)
BuildRequires:  pkgconfig(xt)
BuildRequires:  gettext

%description
X Pixmap (XPM) image file format library


%package devel
Summary:    Development components for the libXpm library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
X Pixmap (XPM) image file format development library



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libXpm.so.4
%{_libdir}/libXpm.so.4.11.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_bindir}/cxpm
%{_bindir}/sxpm
%{_includedir}/X11/xpm.h
%{_libdir}/libXpm.so
%{_libdir}/pkgconfig/xpm.pc
%doc %{_mandir}/man1/*.1*
# << files devel
